apiVersion: batch/v1
kind: Job
metadata:
  name: migration-maple-lms-job
  labels:
    drydock.io/component: job
    drydock.io/target-service: lms
    drydock.io/runner-service: lms
  annotations:
    argocd.argoproj.io/sync-wave: "{{ get_priority('job', 'migration-maple-lms-job') }}"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: lms
        image: {{ DOCKER_IMAGE_OPENEDX }}
        command:
          - /bin/sh
          - -c
          - -e
        args:
        - |
          ./manage.py lms migrate user_tours
          ./manage.py lms backpopulate_user_tours
        env:
        - name: SERVICE_VARIANT
          value: lms
        - name: DJANGO_SETTINGS_MODULE
          value: lms.envs.tutor.production
        volumeMounts:
          - mountPath: /openedx/edx-platform/lms/envs/tutor/
            name: settings-lms
          - mountPath: /openedx/edx-platform/cms/envs/tutor/
            name: settings-cms
          - mountPath: /openedx/config
            name: config
      volumes:
      - name: settings-lms
        configMap:
          name: openedx-settings-lms
      - name: settings-cms
        configMap:
          name: openedx-settings-cms
      - name: config
        configMap:
          name: openedx-config
